name: Question
description: Ask a question about SWE-agent or request documentation that is missing.
labels: ['documentation']

body:
- type: textarea
  attributes:
    label: Describe the issue
    description: >
      Tell us about the confusion you have about SWE-agent *or*
      the information that is missing in the documentation.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggest an improvement to documentation
    description: >
      Tell us how we could improve the documentation in this regard.